test

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -32,8 +32,8 @@ jobs:
       LOG_FILE: log.out
       GH_REPO_PATH: https://raw.githubusercontent.com/$GH_ORG/$GH_REPO/$GH_BRANCH
     outputs:
-      IMAGE_TAG: ${{ steps.script.outputs.IMAGE_TAG }}
-      ECR_LOGIN_PASSWORD: ${{ steps.script.outputs.ECR_LOGIN_PASSWORD }}
+      IMAGE_TAG: ${{ steps.get-output.outputs.IMAGE_TAG }}
+      ECR_LOGIN_PASSWORD: ${{ steps.get-output.outputs.ECR_LOGIN_PASSWORD }}
 
     steps:
       - name: Checkout
@@ -105,12 +105,20 @@ jobs:
           echo ERRORS:
           grep -ni error $LOG_FILE | sed 's/$/\n/'
           if [ -n "$(grep -ni error $LOG_FILE)" ]; then
-              exit 10
+            echo "Errors found"
+            # exit 10
           fi
           echo "No errors found"
-          
+
+      - name: Get ECR login password
+        id: get-output
+        run: |
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
-          echo "ECR_LOGIN_PASSWORD=$(awk -F= '{print $2}' <<< $(grep -E 'ECR_LOGIN_PASSWORD=.*' <<< $res))" >> $GITHUB_OUTPUT
+          if [[ $AWS_CLI_SERVICE == ecr ]]; then
+            echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
+          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
+            echo "ECR_LOGIN_PASSWORD=$(aws ecr-public get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
+          fi
           
 
   # Container network where we can access with the service name and the port
