test

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -101,13 +101,13 @@ jobs:
             DOCKER_FOLDER_PATH=$DOCKER_FOLDER_PATH
 
           echo LOGS: && cat $LOG_FILE
-          echo ERRORS:
-          if grep -ni error $LOG_FILE | sed 's/$/\n/'; then
-              # exit 10
-              echo testtttttttttttttttt
-          else
-              echo "No errors found"
-          fi
+          # echo ERRORS:
+          # if grep -ni error $LOG_FILE | sed 's/$/\n/'; then
+          #     # exit 10
+          #     echo testtttttttttttttttt
+          # else
+          #     echo "No errors found"
+          # fi
           
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
           echo "ECR_LOGIN_PASSWORD=$(awk -F= '{print $2}' <<< $(grep -E 'ECR_LOGIN_PASSWORD=.*' <<< $res))" >> $GITHUB_OUTPUT
