clean sh

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -28,7 +28,7 @@ jobs:
       AWS_CLI_SERVICE: ecr  # private
       DOCKER_FOLDER_PATH: Dockerfile
       IMAGE_TAG: "latest"
-      SCRIPT_NAME: ecr-setup.sh
+      SCRIPT_NAME: ecr-set.sh
       LOG_FILE: log.out
       GH_REPO_PATH: https://raw.githubusercontent.com/$GH_ORG/$GH_REPO/$GH_BRANCH
     outputs:
@@ -38,52 +38,8 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-
-      # - name: setup AWS CLI
-      #   run: |
-      #     aws --version
-      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
-      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
-      #     aws configure set region $AWS_REGION
-
-      # - name: Get ECR login password
-      #   id: get-login-password
-      #   run: |
-      #     if [[ $AWS_CLI_SERVICE == ecr ]]; then
-      #       echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
-      #     elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
-      #       
-      #     fi
-
-      # - name: login to ECR  IMAGE_TAG: "latest"
-      #   run: |
-      #     if [[ $AWS_CLI_SERVICE == ecr ]]; then
-      #       docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-      #     elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
-      #       docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} public.ecr.aws
-      #     fi
-      
-      # - name: Create ECR repository
-      #   run: |
-      #     aws ecr create-repository \
-      #       --repository-name $COMMON_NAME \
-      #       --image-scanning-configuration scanOnPush=true \
-      #       --region $AWS_REGION \
-      #       --output text \
-      #       --query 'repository.repositoryUri'
-
-      # - name: Build, tag, and push image to Amazon ECR
-      #   id: build-image
-      #   env:
-      #     
-      #   run: |
-      #     export ECR_URI=$(aws ecr describe-repositories --repository-names $COMMON_NAME --output text --query "repositories[].[repositoryUri]")
-      #     echo "ECR_URI= $ECR_URI"
-      #     docker build -t $ECR_URI/$IMAGE_TAG -f $DOCKER_FOLDER_PATH .
-      #     docker tag $(docker images -q $ECR_URI/$IMAGE_TAG) $ECR_URI:$IMAGE_TAG
-      #     docker push $ECR_URI:$IMAGE_TAG
-      #     
-      - name: run ECR-setup
+  
+      - name: run ecr-set.sh
         id: script
         run: |
           # curl -o $SCRIPT_NAME https://raw.githubusercontent.com/KookaS/infrastructure-modules/dynamodb/.github/workflows/ecr-create.sh?token=GHSAT0AAAAAACCEOEUUZDBFTBEZS66QJV2OZDS4JMA \
@@ -91,13 +47,10 @@ jobs:
 
           eval res=$(./$SCRIPT_NAME LOG_FILE=$LOG_FILE ECR_CREATE=false AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_SECRET_KEY=$AWS_SECRET_KEY AWS_REGION=$AWS_REGION AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID AWS_CLI_SERVICE=ecr COMMON_NAME=$COMMON_NAME IMAGE_TAG=$IMAGE_TAG DOCKER_FOLDER_PATH=$DOCKER_FOLDER_PATH)
 
-          echo LOGS: && cat $LOG_FILE
-          echo ERRORS:
-          grep -ni error $LOG_FILE | sed 's/$/\n/'
-          if [ -n "$(grep -i error $LOG_FILE)" ]; then
-            exit 10
+          echo echo -e '\033[1mLOGS\033[0m': && cat $LOG_FILE
+          if [ -n "$(grep -i error $LOG_FILE)" ]; then 
+            echo -e '\033[1mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 10
           fi
-          echo "No errors found"
 
       - name: Get ECR login password
         id: get-output
@@ -265,6 +218,8 @@ jobs:
     environment: KookaS
     env:
       AWS_CLI_SERVICE: ecr  # private
+      SCRIPT_NAME: ecr-clean.sh
+      LOG_FILE: log.out
     outputs:
       IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
       ECR_LOGIN_PASSWORD: ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }}
@@ -273,29 +228,18 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: setup AWS CLI
+      - name: run ecr-clean.sh
+        id: script
         run: |
-          aws --version
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
-          aws configure set region $AWS_REGION
+          # curl -o $SCRIPT_NAME https://raw.githubusercontent.com/KookaS/infrastructure-modules/dynamodb/.github/workflows/ecr-create.sh?token=GHSAT0AAAAAACCEOEUUZDBFTBEZS66QJV2OZDS4JMA \
+          chmod +x $SCRIPT_NAME
 
-      - name: login to ECR
-        run: |
-          if [[ $AWS_CLI_SERVICE == ecr ]]; then
-            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
-            aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws
-          fi
-      
-      - name: Delete ECR repository
-        run: |
-          aws ecr delete-repository \
-            --repository-name $COMMON_NAME \
-            --force \
-            --region $AWS_REGION \
-            --output text \
-            --query 'repository.registryId'
+          eval res=$(./$SCRIPT_NAME LOG_FILE=$LOG_FILE AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_SECRET_KEY=$AWS_SECRET_KEY AWS_REGION=$AWS_REGION AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID AWS_CLI_SERVICE=ecr COMMON_NAME=$COMMON_NAME)
+
+          echo echo -e '\033[1mLOGS\033[0m': && cat $LOG_FILE
+          if [ -n "$(grep -i error $LOG_FILE)" ]; then 
+            echo -e '\033[1mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 10
+          fi          
 
       - name: Delete Dynamodb tables
         if: ${{ always() && contains(join(needs.dynamodb.result, ','), 'success') }}
