test

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -105,14 +105,15 @@ jobs:
           #   IMAGE_TAG=$IMAGE_TAG \
           #   DOCKER_FOLDER_PATH=$DOCKER_FOLDER_PATH
 
-          # echo LOGS: && cat $LOG_FILE
-          # echo ERRORS:
-          # if grep -ni error $LOG_FILE | sed 's/$/\n/'; then
-          #     # exit 10
-          #     echo testtttttttttttttttt
-          # else
-          #     echo "No errors found"
-          # fi
+          echo LOGS: && cat $LOG_FILE
+
+          echo ERRORS:
+          grep -ni error $LOG_FILE | sed 's/$/\n/'
+          if [ -n "$(grep -ni error $LOG_FILE)" ]; then
+              echo "testtttttttttttttttt"
+              # exit 10
+          fi
+          echo "No errors found"
           
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
           echo "ECR_LOGIN_PASSWORD=$(awk -F= '{print $2}' <<< $(grep -E 'ECR_LOGIN_PASSWORD=.*' <<< $res))" >> $GITHUB_OUTPUT
