no log

diff --git a/.github/workflows/ecr.yml b/.github/workflows/ecr.yml
--- a/.github/workflows/ecr.yml
+++ b/.github/workflows/ecr.yml
@@ -47,10 +47,10 @@ jobs:
       - name: Run script
         id: script
         run: |
-          # log
-          exec 3>&1 4>&2
-          trap 'exec 2>&4 1>&3' 0 1 2 3
-          exec 1>$LOG_FILE 2>&1
+          # # log
+          # exec 3>&1 4>&2
+          # trap 'exec 2>&4 1>&3' 0 1 2 3
+          # exec 1>$LOG_FILE 2>&1
 
           # setup AWS CLI
           aws --version
@@ -122,7 +122,7 @@ jobs:
 
           fi
 
-          echo -e '\033[46mLOGS\033[0m'; cat $LOG_FILE
-          if [ -n "$(grep -i error $LOG_FILE)" ]; then
-            echo -e '\033[41mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 100
-          fi
+          # echo -e '\033[46mLOGS\033[0m'; cat $LOG_FILE
+          # if [ -n "$(grep -i error $LOG_FILE)" ]; then
+          #   echo -e '\033[41mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 100
+          # fi
