functions

diff --git a/.github/workflows/ecr.yml b/.github/workflows/ecr.yml
--- a/.github/workflows/ecr.yml
+++ b/.github/workflows/ecr.yml
@@ -1,4 +1,4 @@
-name: ECR Create
+name: ECR
 
 on:
   workflow_dispatch:
@@ -25,14 +25,11 @@ env:
   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
   AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
   AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
-  ECR_ORG: KookaS
-  ECR_REPO: infrastructure-modules
-  ECR_BRANCH: master
+  AWS_CLI_SERVICE: ecr
   ECR_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
-  DOCKER_FOLDER_PATH: ./Dockerfile
-  ECR_IMAGE_TAG_THIS: ${{ github.sha }}
-  AWS_CLI_ECR: ecr
-  BRANCH_THIS: ${{ github.head_ref || github.ref_name }}
+  DOCKERFILES: (./Dockerfile)
+  IMAGE_TAG: ${{ github.sha }}
+  BRANCH: ${{ github.head_ref || github.ref_name }}
 
 jobs:
   ecr:
@@ -54,75 +51,76 @@ jobs:
           aws configure set region $AWS_REGION
 
           # login to ECR
-          if [[ $AWS_CLI_ECR == ecr ]]; then
+          if [[ $AWS_CLI_SERVICE == ecr ]]; then
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
-          elif [[ $AWS_CLI_ECR == ecr-public ]]; then
+          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
             aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS ---password-stdin public.ecr.aws
           fi
 
           # setup variables
-          ECR_REPOSITORY_NAME_SRC="$(echo ${ECR_ORG}-${ECR_REPO}-${ECR_BRANCH} | tr A-Z a-z)"
-          ECR_IMAGE_TAG_SRC="${{ inputs.image-tag }}"
-          ECR_IMAGE_TAG_SRC="${ECR_IMAGE_TAG_SRC:-latest}"
-          ECR_REPOSITORY_NAME_THIS="$(echo ${{ github.repository_owner }}-$(basename ${{ github.repository }})-${BRANCH_THIS} | tr A-Z a-z)"
-          IMAGE_KEEP_COUNT=$(if [[ $BRANCH_THIS == master ]]; then echo "5"; else echo "1"; fi)
           echo "event_name=${{ github.event_name }}"
           echo "inputs.event=${{ inputs.event }}"
-          echo "ECR_REPOSITORY_NAME_SRC: $ECR_REPOSITORY_NAME_SRC"
-          echo "ECR_IMAGE_TAG_SRC: $ECR_IMAGE_TAG_SRC"
-          echo "ECR_REPOSITORY_NAME_THIS: $ECR_REPOSITORY_NAME_THIS"
+          IMAGE_KEEP_COUNT=$(if [[ $BRANCH == master ]]; then echo "5"; else echo "1"; fi)
           echo "IMAGE_KEEP_COUNT: $IMAGE_KEEP_COUNT"
 
-          # create/push/delete ECR
-          if [[ "${{ github.event_name }}" == "create" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "create") ]]; then
-
+          # setup function
+          func_ecr_create () {
             echo -e '\033[43mCreating repository in ECR\033[0m'
-            aws $AWS_CLI_ECR create-repository --repository-name ${ECR_REPOSITORY_NAME_THIS} --image-tag-mutability MUTABLE --tags Key=Account,Value=$AWS_PROFILE Key=Region,Value=$AWS_REGION Key=Organization,Value=${{ github.repository_owner }} Key=Repository,Value=$(basename ${{ github.repository }}) Key=Branch,Value=$BRANCH_THIS
+            aws $AWS_CLI_SERVICE create-repository --repository-name $ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION --image-tag-mutability MUTABLE --tags Key=Account,Value=$AWS_PROFILE Key=Region,Value=$AWS_REGION Key=Organization,Value=${{ github.repository_owner }} Key=Repository,Value=$(basename ${{ github.repository }}) Key=Branch,Value=$BRANCH
             json_string=$(
               jq --null-input \
                 --argjson count "${IMAGE_KEEP_COUNT}" \
                 '{rules: [ { rulePriority: 1, description: "Keep only \($count) images", selection: { tagStatus: "any", countType: "imageCountMoreThan", countNumber: $count }, action: { type: "expire" } } ] }'
             )
             echo $json_string > ecr-lifecycle-policy.json
-            aws $AWS_CLI_ECR put-lifecycle-policy --repository-name ${ECR_REPOSITORY_NAME_THIS} --lifecycle-policy-text "file://ecr-lifecycle-policy.json"
-
-          elif [[ "${{ github.event_name }}" == "push" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "push") ]]; then
-
-            REPOSITORY_NAME_EXISTING=$(aws $AWS_CLI_ECR describe-repositories --repository-names ${ECR_REPOSITORY_NAME_THIS} --query 'repositories[0].repositoryName' || true)
+            aws $AWS_CLI_SERVICE put-lifecycle-policy --repository-name $ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION --lifecycle-policy-text "file://ecr-lifecycle-policy.json"
+          }
+          func_ecr_push () {
+            # check existance of repository
+            REPOSITORY_NAME_EXISTING=$(aws $AWS_CLI_SERVICE describe-repositories --repository-names $ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION --query 'repositories[0].repositoryName' || true)
             echo REPOSITORY_NAME_EXISTING=$REPOSITORY_NAME_EXISTING
-              if [ -z ${REPOSITORY_NAME_EXISTING} ]; then
-                aws $AWS_CLI_ECR create-repository --repository-name ${ECR_REPOSITORY_NAME_THIS} --image-tag-mutability MUTABLE --tags Key=Account,Value=$AWS_PROFILE Key=Region,Value=$AWS_REGION Key=Organization,Value=${{ github.repository_owner }} Key=Repository,Value=$(basename ${{ github.repository }}) Key=Branch,Value=$BRANCH_THIS
-                json_string=$(
-                  jq --null-input \
-                    --argjson count "${IMAGE_KEEP_COUNT}" \
-                    '{rules: [ { rulePriority: 1, description: "Keep only \($count) images", selection: { tagStatus: "any", countType: "imageCountMoreThan", countNumber: $count }, action: { type: "expire" } } ] }'
-                )
-                echo $json_string > ecr-lifecycle-policy.json
-                aws $AWS_CLI_ECR put-lifecycle-policy --repository-name ${ECR_REPOSITORY_NAME_THIS} --lifecycle-policy-text "file://ecr-lifecycle-policy.json"
-              else
-                echo -e '\033[46mRepository already exists\033[0m'
-              fi
+            if [ -z ${REPOSITORY_NAME_EXISTING} ]; then
+              func_ecr_create
+            else
+              echo -e '\033[46mRepository already exists\033[0m'
+            fi
 
-              echo -e '\033[43mPushing image to ECR\033[0m'
-              docker build --progress=plain --no-cache -t $ECR_URI/$ECR_REPOSITORY_NAME_THIS/$ECR_IMAGE_TAG_THIS -f ${DOCKER_FOLDER_PATH} .
-              DOCKER_SRC=$(docker images -q $ECR_URI/$ECR_REPOSITORY_NAME_THIS/$ECR_IMAGE_TAG_THIS)
-              echo -e '\033[44mIMAGE SIZE\033[0m' $(docker inspect -f "{{ .Size }}" ${DOCKER_SRC} | numfmt --to=si)
-              docker tag ${DOCKER_SRC} $ECR_URI/$ECR_REPOSITORY_NAME_THIS:$ECR_IMAGE_TAG_THIS
-              docker push $ECR_URI/$ECR_REPOSITORY_NAME_THIS:$ECR_IMAGE_TAG_THIS
-              docker tag $ECR_URI/$ECR_REPOSITORY_NAME_THIS:$ECR_IMAGE_TAG_THIS $ECR_URI/$ECR_REPOSITORY_NAME_THIS:latest
-              docker push $ECR_URI/$ECR_REPOSITORY_NAME_THIS:latest
+            # Push new image
+            echo -e '\033[43mPushing image to ECR\033[0m'
+            docker build --progress=plain --no-cache -t $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION/$IMAGE_TAG -f ${DOCKERFILES} .
+            DOCKER_SRC=$(docker images -q $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION/$IMAGE_TAG)
+            echo -e '\033[44mIMAGE SIZE\033[0m' $(docker inspect -f "{{ .Size }}" ${DOCKER_SRC} | numfmt --to=si)
+            docker tag ${DOCKER_SRC} $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION:$IMAGE_TAG
+            docker push $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION:$IMAGE_TAG
+            docker tag $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION:$IMAGE_TAG $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION:latest
+            docker push $ECR_URI/$ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION:latest
 
-              echo -e '\033[44mECR IMAGE THIS\033[0m'::
-              aws $AWS_CLI_ECR describe-images --repository-name ${ECR_REPOSITORY_NAME_THIS} --image-ids imageTag=latest --output json
+            # Describe new image
+            echo -e '\033[44mECR IMAGE THIS\033[0m'::
+            aws $AWS_CLI_SERVICE describe-images --repository-name $ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION --image-ids imageTag=latest --output json
+          }
+          func_ecr () {
+            # create/push/delete
+            if [[ "${{ github.event_name }}" == "create" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "create") ]]; then
+              func_ecr_create
+            elif [[ "${{ github.event_name }}" == "push" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "push") ]]; then
+              func_ecr_push
+            elif [[ "${{ github.event_name }}" == "delete" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "delete") ]]; then
+              echo -e '\033[43mDeleting repository in ECR\033[0m'
+              aws ecr delete-repository --repository-name $ECR_REPOSITORY_NAME$DOCKERFILE_EXTENSION --force
+            else
+              echo -e '\033[41mError\033[0m'
+              echo Error: event do not match, event_name ${{ github.event_name }}, inputs.event ${{ inputs.event }}
+              exit 100
+            fi
+          }
 
-          elif [[ "${{ github.event_name }}" == "delete" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.event }}" == "delete") ]]; then
+          for DOCKERFILE in ${DOCKERFILES[@]}; do
+            # extract possible extension
+            DOCKERFILE_EXTENSION=$([[ "$DOCKERFILE" = *.* ]] && echo "-${DOCKERFILE##*.}" || echo '')
+            ECR_REPOSITORY_NAME="$(echo ${{ github.repository_owner }}-$(basename ${{ github.repository }})-${BRANCH}$DOCKERFILE_EXTENSION | tr A-Z a-z)"
+            echo "ECR_REPOSITORY_NAME: $ECR_REPOSITORY_NAME"
+            func_ecr
+          done
 
-            echo -e '\033[43mDeleting repository in ECR\033[0m'
-            aws ecr delete-repository --repository-name $ECR_REPOSITORY_NAME_THIS --force
-
-          else
-
-            echo -e '\033[41mError\033[0m'
-            echo Error: event do not match, event_name ${{ github.event_name }}, inputs.event ${{ inputs.event }}
-            exit 100
-          fi
+          
